;	RUN #1
play_00:	.db "WTE", SPACE, "OFFTACKLE", SPACE, "R"
play_01:	.db "ONESETBACK", SPACE, "L"
play_02:	.db "R", SPACE, "S", SPACE, "SWEEP", SPACE, "L"
play_03:	.db "FB", SPACE, "OFFTACKLE", SPACE, "R"
play_04:	.db "FB", SPACE, "OPEN", SPACE, "L"
play_05:	.db "TOSS", SPACE, "SWEEP", SPACE, "R"
play_06:	.db "T", SPACE, "FAKE", SPACE, "SWEEP", SPACE, "R"
play_07:	.db "T", SPACE, "POWER", SPACE, "SWEEP", SPACE, "R"
;	RUN #2
play_08:	.db "R", SPACE, "S", SPACE, "DRAW"
play_09:	.db "PITCH", SPACE, "L", SPACE, "FAKE"
play_10:	.db "ONEBACK", SPACE, "SWEEP", SPACE, "R"
play_11:	.db "WEAKSIDE", SPACE, "OPEN"
play_12:	.db "T", SPACE, "OFFTACKLE", SPACE, "R"
play_13:	.db "T", SPACE, "SWEEP", SPACE, "STRONG"
play_14:	.db "T", SPACE, "POWER", SPACE, "DIVE"
play_15:	.db "FB", SPACE, "OFFTACKLE", SPACE, "L"
;	RUN #3
play_16:	.db "T", SPACE, "CROSS", SPACE, "RUN", SPACE, "L"
play_17:	.db "SLOT", SPACE, "OFFTACKLE"
play_18:	.db "CROSS", SPACE, "OFFTACKLE"
play_19:	.db "PITCH", SPACE, "L", SPACE, "OPEN"
play_20:	.db "WR", SPACE, "REVERSE", SPACE, "R"
play_21:	.db "WR", SPACE, "REVERSE", SPACE, "L"
play_22:	.db "SHOTGUN", SPACE, "DRAW"
play_23:	.db "R", SPACE, "AND", SPACE, "S", SPACE, "SWEEP", SPACE, "R"
;	RUN #4
play_24:	.db "R", SPACE, "AND", SPACE, "S", SPACE, "QBSNEAK"
play_25:	.db "ONESETBACK", SPACE, "DIVE"
play_26:	.db "PRO", SPACE, "T", SPACE, "DIVE"
play_27:	.db "FB", SPACE, "POWER", SPACE, "DIVE"
play_28:	.db "SHOTGUN", SPACE, "C", SPACE, "DRAW"
play_29:	.db "REVERSE", SPACE, "PITCH", SPACE, "R"
play_30:	.db "R", SPACE, "AND", SPACE, "S", SPACE, "QB", SPACE, "RUN"
play_31:	.db "SHOTGUN", SPACE, "SWEEP", SPACE, "L"
;	PASS #1
play_32:	.db "PRO", SPACE, "T", SPACE, "WAGGLE", SPACE, "R"
play_33:	.db "ROLL", SPACE, "OUT", SPACE, "R"
play_34:	.db "ROLL", SPACE, "OUT", SPACE, "L"
play_35:	.db "T", SPACE, "PLAY", SPACE, "ACTION", SPACE, "D"
play_36:	.db "PRO", SPACE, "T", SPACE, "SCREEN", SPACE, "L"
play_37:	.db "PLAY", SPACE, "ACTION"
play_38:	.db "PRO", SPACE, "T", SPACE, "WAGGLE", SPACE, "L"
play_39:	.db "R", SPACE, "AND", SPACE, "S", SPACE, "FLARE", SPACE, "C"
;	PASS #2
play_40:	.db "SHOTGUN", SPACE, "X", SPACE, "CURL"
play_41:	.db "R", SPACE, "AND", SPACE, "S", SPACE, "Z", SPACE, "FLY"
play_42:	.db "PRO", SPACE, "T", SPACE, "FLARE", SPACE, "D"
play_43:	.db "OFFSET", SPACE, "FLARE", SPACE, "E"
play_44:	.db "ONEBACK", SPACE, "Z", SPACE, "CROSS"
play_45:	.db "ONEBACK", SPACE, "FLARE", SPACE, "A"
play_46:	.db "POWER", SPACE, "FAKE", SPACE, "Z", SPACE, "POST"
play_47:	.db "WTE", SPACE, "F", DASH, "FLICKER"
;	PASS #3
play_48:	.db "SHOTGUN", SPACE, "X", SPACE, "DRIVE"
play_49:	.db "R", SPACE, "AND", SPACE, "S", SPACE, "3", DASH, "WING"
play_50:	.db "PLAYACTION", SPACE, "Z", SPACE, "IN"
play_51:	.db "FLEA", SPACE, "FLICKER"
play_52:	.db "PRO", SPACE, "T", SPACE, "FLARE", SPACE, "C"
play_53:	.db "SHOTGUN", SPACE, "3", DASH, "WING"
play_54:	.db "T", SPACE, "FLEA", SPACE, "FLICKER"
play_55:	.db "PWR", SPACE, "FAKE", SPACE, "X", SPACE, "FLY"
;	PASS #4
play_56:	.db "X", SPACE, "OUT", SPACE, "AND", SPACE, "FLY"
play_57:	.db "REV", DASH, "FAKE", SPACE, "Z", SPACE, "POST"
play_58:	.db "SLOT", SPACE, "L", SPACE, "Z", SPACE, "DRIVE"
play_59:	.db "NO", SPACE, "BACK", SPACE, "X", SPACE, "DEEP"
play_60:	.db "SHOTGUN", SPACE, "Z", SPACE, "S", DASH, "IN"
play_61:	.db "REDGUN", SPACE, "Z", SPACE, "SLANT"
play_62:	.db "SHOTGUN", SPACE, "XY", SPACE, "BOMB"
play_63:	.db "R", SPACE, "AND", SPACE, "S", SPACE, "Y", SPACE, "UP"
eof: